name: MVulD-CPU 
channels:
  - conda-forge 
  - defaults
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
dependencies:
  - python=3.8 
  - pip
  - pytorch
  - torchvision
  - torchaudio 
  - pip:
    - absl-py==1.0.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - altair==4.2.0
    - anyio==3.5.0
    - apex==0.1
    - argh==0.26.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - async-timeout==4.0.2
    - attrs==21.4.0
    - babel==2.10.1
    - beautifulsoup4==4.11.1
    - bleach==5.0.0
    - blessings==1.7
    - blis==0.7.9
    - cachetools==5.0.0
    - catalogue==2.0.7
    - click==8.1.3
    - conda-pack==0.6.0
    - confection==0.0.3
    - cramjam==2.5.0
    - cxxfilt==0.3.0
    - cycler==0.11.0
    - cymem==2.0.6
    - cython==0.29.32
    - defusedxml==0.7.1
    - dgl-cu102==0.8.1
    - dill==0.3.4
    - distlib==0.3.4
    - fastjsonschema==2.15.3
    - fastparquet==0.8.1
    - filelock==3.6.0
    - flawfinder==2.0.19
    - fonttools==4.33.3
    - frozenlist==1.3.0
    - fsspec==2022.3.0
    - gensim==3.8.0
    - google-auth==2.6.6
    - google-auth-oauthlib==0.4.6
    - gpustat==0.6.0
    - gputil==1.4.0
    - grpcio==1.43.0
    - h11==0.12.0
    - httpcore==0.15.0
    - httpx==0.23.0
    - huggingface-hub==0.5.1
    - igraph==0.9.10
    - imageio==2.19.3
    - imbalanced-learn==0.9.0
    - importlib-metadata==4.11.3
    - importlib-resources==5.7.1
    - imutils==0.5.4
    - iniconfig==1.1.1
    - ipython-genutils==0.2.0
    - jinja2==3.1.2
    - joblib==1.1.0
    - json5==0.9.8
    - jsonschema==4.5.1
    - jupyter-server==1.17.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.13.0
    - jupyterlab-widgets==1.1.0
    - kiwisolver==1.4.2
    - langcodes==3.3.0
    - lanms==1.0.2
    - lmdb==1.3.0
    - markdown==3.3.7
    - markupsafe==2.1.1
    - matplotlib==3.5.2
    - mistune==0.8.4
    - msgpack==1.0.3
    - multidict==6.0.2
    - murmurhash==1.0.7
    - nbclassic==0.3.7
    - nbclient==0.6.3
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - networkx==2.8
    - nltk==3.7
    - notebook==6.4.11
    - notebook-shim==0.1.0
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.2.0
    - opencv-contrib-python==4.6.0.66
    - opencv-python==4.6.0.66
    - pandas==1.4.2
    - pandocfilters==1.5.0
    - pathy==0.6.1
    - pkgtools==0.7.3
    - platformdirs==2.5.2
    - pluggy==1.0.0
    - polygon==1.1.0
    - polygon3==3.0.9.1
    - preshed==3.0.6
    - prettytable==3.3.0
    - prometheus-client==0.14.1
    - protobuf==3.20.1
    - py==1.11.0
    - pyarrow==8.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==1.8.2
    - pydeprecate==0.3.2
    - pyg==0.7.1
    - pyrsistent==0.18.1
    - pytesseract==0.3.10
    - pytest==7.1.2
    - pytorch-lightning==1.6.3
    - pytz==2022.1
    - pywavelets==1.3.0
    - pyyaml==6.0
    - randomwords==0.4.0
    - ray==1.12.0
    - regex==2022.4.24
    - requests-oauthlib==1.3.1
    - rfc3986==1.5.0
    - rsa==4.8
    - sacremoses==0.0.53
    - scikit-image==0.19.3
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - seaborn==0.11.2
    - send2trash==1.8.0
    - shapely==1.8.5.post1
    - smart-open==5.2.1
    - sniffio==1.2.0
    - soupsieve==2.3.2.post1
    - spacy==3.4.1
    - spacy-legacy==3.0.9
    - spacy-loggers==1.0.2
    - srsly==2.4.3
    - tabulate==0.8.9
    - tensorboard==2.9.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5
    - termcolor==1.1.0
    - terminado==0.13.3
    - texttable==1.6.4
    - thinc==8.1.4
    - threadpoolctl==3.1.0
    - tifffile==2022.5.4
    - timm==0.4.12
    - tinycss2==1.1.1
    - tokenizers==0.12.1
    - tomli==2.0.1
    - toolz==0.12.0
    - torch==1.10.0+cu113
    - torch-geometric==2.0.4
    - torchinfo==1.6.5
    - torchmetrics==0.8.2
    - torchprofile==0.0.4
    - torchsummary==1.5.1
    - torchtext==0.11.0
    - torchtoolbox==0.1.8.2
    - tqdm==4.64.0
    - transformers==4.18.0
    - tsne-torch==1.0.1
    - typer==0.4.1
    - ujson==5.2.0
    - unidecode==1.3.4
    - unidiff==0.7.3
    - vega-datasets==0.9.0
    - virtualenv==20.14.1
    - wasabi==0.9.1
    - webencodings==0.5.1
    - websocket-client==1.3.2
    - websockets==10.3
    - werkzeug==2.1.2
    - widgetsnbextension==3.6.0
    - xgboost==1.6.1
    - yacs==0.1.8
    - yarl==1.7.2
    - zipp==3.8.0
